# Generated by Django 4.1.3 on 2023-05-27 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imagem_capa_post_resumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 27, 2, 54, 25, 74634, tzinfo=datetime.timezone.utc)),
        ),
    ]
